# Codecov configuration for nightowl R package
# Documentation: https://docs.codecov.io/docs/codecov-yaml

codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

  ignore:
    - "man/"
    - "inst/"
    - "vignettes/"
    - "tests/"
    - "docs/"
    - "*.md"
    - "*.Rmd"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

github_checks:
  annotations: true