test_that("calc_summary spreads data-frame results and keeps plots", {
  res <- calc_summary(dplyr::group_by(mtcars, cyl), "mpg",
                      calculations = list(N = length, Mean = format_mean_ci, PR = add_inline_pointrange))
  expect_s3_class(res, "grouped_df")
  expect_equal(dplyr::group_vars(res), "cyl")
  expect_named(res, c("cyl", "Variable", "N", "Mean", "CI", "PR"))
  expect_equal(res$N, as.vector(table(mtcars$cyl)))
  expect_true(is_NightowlPlots(res$PR))
  expect_equal(nrow(res), 3)
  expect_equal(res$Variable, rep("mpg", 3))
})

test_that("calc_summary respects unnest = FALSE, parameters and templates", {
  nested <- calc_summary(mtcars, "mpg", calculations = list(Mean = format_mean_ci), unnest = FALSE)
  expect_type(nested$Mean, "list")
  expect_s3_class(nested$Mean[[1]], "tbl_df")
  param <- calc_summary(mtcars, "mpg", calculations = list(Test = function(x, what) what),
                        parameters = list(Test = list(what = "hi")))
  expect_equal(param$Test, "hi")
  tpl <- calc_summary(dplyr::group_by(mtcars, cyl), "mpg", template = summarise_numeric)
  expect_equal(tpl$Median, as.vector(tapply(mtcars$mpg, mtcars$cyl, median)))
  expect_message(calc_summary(mtcars, "mpg"), "counting")
  expect_error(calc_summary(mtcars, "nope"), "not present")
  expect_error(calc_summary(mtcars, "mpg", calculations = list(function(x) 1)), "named list")
  expect_error(calc_summary(mtcars, "mpg", calculations = list(Bad = function(x) data.frame(a = 1:2))), "one row")
  vec <- calc_summary(mtcars, "mpg", calculations = list(R = range))
  expect_type(vec$R, "list")
})

test_that("templates share axis limits when given a summary", {
  s <- list(data = mtcars, column = "mpg")
  tpl <- summarise_numeric_pointrange(s)
  expect_equal(tpl$parameters$Pointrange$xlim, range(mtcars$mpg))
  expect_null(summarise_numeric_pointrange()$parameters$Pointrange)
  over <- summarise_numeric_histogram(s, Histogram = list(height = 2))
  expect_equal(over$parameters$Histogram$height, 2)
  expect_true(all(c("N", "Freq", "Barplot") %in% names(summarise_categorical_barplot()$calculations)))
})

test_that("Summary infers groups, method and test", {
  s <- Summary$new(dplyr::group_by(mtcars, cyl), "mpg")
  expect_equal(s$group_by, "cyl")
  expect_identical(s$method, summarise_numeric)
  raw <- s$raw()
  expect_equal(raw$Median, as.vector(tapply(mtcars$mpg, mtcars$cyl, median)))
  expect_match(s$footnote(), "Kruskal-Wallis")
  expect_equal(s$test()$p_value, stats::kruskal.test(mpg ~ cyl, mtcars)$p.value)
  expect_equal(s$caption(), "Summary of mpg")
  cat_s <- Summary$new(transform(mtcars, am = factor(am)), "am", group_by = "cyl")
  expect_identical(cat_s$method, summarise_categorical)
  expect_match(cat_s$footnote(), "chi-squared")
  expect_named(cat_s$raw(), c("cyl", "Variable", "N", "0", "1"))
})

test_that("Summary options, labels and errors", {
  expect_error(Summary$new(mtcars, "nope"), "not present")
  expect_error(Summary$new(mtcars, "mpg", facet = 1), "unused argument")
  s <- Summary$new(mtcars, "mpg", group_by = "cyl", labels = c(mpg = "Miles per gallon", cyl = "Cylinders"),
                   add_test = FALSE, keep_variable = FALSE, arrange_by = "Median")
  raw <- s$raw()
  expect_null(s$test())
  expect_null(s$footnote())
  expect_false("Variable" %in% names(raw))
  expect_equal(names(raw)[1], "Cylinders")
  expect_equal(s$caption(), "Summary of Miles per gallon")
  expect_true(!is.unsorted(raw$Median))
  ungrouped <- Summary$new(mtcars, "mpg")
  expect_false(ungrouped$add_test)
  expect_equal(nrow(ungrouped$raw()), 1)
  expect_equal(nrow(s$raw(drop = "Min")), 3)
  expect_false("Min" %in% names(s$raw(drop = "Min")))
})

test_that("Summary renders to kable, html and reactable", {
  s <- Summary$new(mtcars, "mpg", group_by = "cyl", method = summarise_numeric_pointrange)
  k <- s$kable()
  expect_s3_class(k, "kableExtra")
  expect_match(k, "<table")
  expect_match(k, "<svg")
  h <- s$html()
  expect_s3_class(h, "shiny.tag")
  r <- s$reactable()
  expect_s3_class(r, "shiny.tag")
  expect_output(print(s), "Summary of mpg")
})

test_that("a failing test is reported, not thrown", {
  local_mocked_bindings(calc_group_test = function(...) stop("boom"))
  s <- Summary$new(mtcars, "mpg", group_by = "cyl")
  expect_true(is.na(s$test()$p_value))
  expect_match(s$footnote(), "Test failed")
})
