on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-coverage-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-coverage-

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::bench, any::ggplot2
          needs: coverage

      - name: Run performance benchmarks
        run: |
          cat("⚡ Running performance benchmarks...\n")
          
          # Check if performance benchmark tests exist
          if (file.exists("tests/testthat/test-performance-benchmarks.R")) {
            # Run performance benchmarks and capture results
            benchmark_results <- testthat::test_file("tests/testthat/test-performance-benchmarks.R", reporter = "summary")
            cat("✅ Performance benchmarks completed\n")
          } else {
            cat("ℹ️  No performance benchmark tests found\n")
          }
        shell: Rscript {0}

      - name: Test coverage
        run: |
          covr::codecov(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
          )
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package